travis:
  secure:
    BINSTAR_TOKEN: SXEJbYicErbJ+rpwc+KU628OpjHELxjhPMCdWRM0dv1KUHz7AsL+6BgvdEInzZFSDCn/BfK7jdAEbAuEnJycIe6gBjRc1orvAzEsgQ1WO9laNVt2zTz5s+qPVuciBv43UNLGlFctEVWpEy1IAKjgk/rTC2ZIDReAjG6y3hLogN4jcwW5O3E5x164fgkcNNAQco6AlpxN5HXjUwEHNEJieZMlazJ6RMDQLPDAsaD84H3fFfUrgg1WK1ReQWZsqr9oyXwR2wwbVj/RzyWYBUkhu9kv1GD0F/lsoyjrLAPD3GZcektRHuay1+gT0rVoPvbvJAK2GDdQdPkMZCqtz7bSTB8y6Cnf3RdJpWZ+GwKqvrGwzPntfhWYwGfRLlkZweV/sIgT89gZ/LQadpjdJn9X59Y/rRfRm9UNAp5QjP57nXYpCEyz9OlxbXlNBdMgoURNKmKDX6euMD4jZggXMM39dhqpad+1WQysn6WCIbPOduTZpSreqDDBBRuHJfEveydP5ISZ3U7dIE4ctSZbpjmxGIx8zRzwRAkQZBAWe1LV26C0kgvdmx7ViE/QFKcmctfE+a0WTJTV8cxSGXULra1dPP4LuD+pk4mCLkwNIY97NV3jp+T6tG8Do0MgwDMLyMtLk2RDlLmdvxilT3n60bn9nTMykezv8ofAnxJdDbVwU58=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
