travis:
  secure:
    BINSTAR_TOKEN: Q5kzLw2A4bROOIJYU1gp5i1S+H82qb0nNN5YMEpU2BntzAOhrwIl6452HyaKStEpxBb0r41gzSaqm2v1O0Uy4+tQF8w64O5T1ILh9SjhG0binrkLaMgo2oFKRN1Z6JNfCbMrA39v9A3+jdVb4SgJTHjIMxuFwYx1hpsMo41aKE9JhqFIxqSdQfS7xArpJ2Hz43sZuIDu/T/6KH39qQO+WtNLyrQqTCKrV7t1NrRgVj2mgHaCfvzaWkaT1F9EdEohTbupCNbfyP+qxbJjcZamHHgM+fGpDtjaMWBpq6jIAF/da3RJGEKaqN0JL91wnmuXVFSteghnk+O9vqvNgW/WbbrxInZNyKCzBmxi20qzKibjrMDan1jIal3HmN3fwlaBL/WuHpoE1mKUzuCUWm7MfYWvv69eiI5Ud+UaDvNZWTFI7fPoaQuirSPEIMXa8cFTLQr7PS8OIrrQDameTPvKevJXnSD8uQ0w8kHBfwMMcRIz4UMZmHjc7iS9twccUXLK/VK0SfjpJ7hw02N1dVW+YQUTzS1ecCl0+UcwCNa/eFuHRK5zG58xp2Gj2p4cOPumrbGNRSGjmPuxsDOxIygNBzGydjY5y3K5rnLmfEnR2XXTKmVsS9cuxVlmG+wFfom9VZbcq3f9mfcronhFjYnKbWDIyb9WLOWklv10rE74j/Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
