travis:
  secure:
    BINSTAR_TOKEN: RJy89xumjV/878VwBmU00WjSE55zR69t4xl1OfcH0YINz2MbXPuthP27HYMRiC8DYVHYLOOSaL3QCTO9AcOu7P9O5E0l0TyKP2lG58rc7/dHPgWi1D2a46dycs0doYq+CY7loYTsoZeLpkrV83GREzvrmhm9XZUu4/1wCeX2VhqIVymzY1woGrZuJLoDo/T6+4zZ471CUvdCh5tbRYraQ2t9Xu3rhZTjUhKEhVnAO2K4bfk46y75OntzGLPlyf50WGoRPPsTUUgeLDmnk+0U1WnF1Gvqf0kdOhrWSwELgZEGRvtLbDyCqPeXKK+pWJxsB2KGhVERUkWiQ0DgFttVRHtGGPkcJjHx+HBQ5l4m1f6ODzz3UZCP3wwwhv8WAfbvp17iYF8YiEyZSmui9Woj1RIQMj8A5Rfj2TlkPMNh1aqvpULaDJMSlX2BsI3wHDsrvRa3lIg7DBMXIdJahHYrzXDyikSrsRcUok2rX4gqBex3KVAQgq9WZJXUrCsWb88nEA+I4FjnHo7XKdKD3GwhjgAiixTvMEHwoNbBawuZvJi0IIUHeOqG3kBFaVGVho7GQ2NoYnUBXNqTbAcq9QbYJZbYt48gilN7GIhTg9hE63TihswmJD3AwN/x2ltpd8/lw85iqhdsZHZib0kV27FrcGCYOnfSzhp1G62tk57HgO0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
